[package]
name = "plankalkul"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.0"
num = "0.3.1"
