[package]
edition = "2018"
name = "plankalkul-pwa"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2"
yew = "^0.17"
plankalkul = { path = "../plankalkul" }
