name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate HTML
      run: docker run -t --rm -v $(pwd):/app -w /app alexpdp7/rust-wasm-pack-rollup ./build-pwa
    - name: Publish
      run: |
        git config --global user.email "alex@pdp7.net"
        git config --global user.name "GitHub Actions"
        cd target/pwa
        sudo chown -R $(id -un) .
        mv ../../.git .
        git branch -M gh-pages
        git add -f .
        git commit -m 'Deploy'
        git push --force origin HEAD
